<div class="hero-unit">

<div class="row" style='margin-top:20px;'>
    <div class="span5 btn">
    <h3><?php echo sprintf($this->translate('Hayallerini paylaş, hayallerine bir adım daha %s yaklaş%s'), '<span class="">', '</span>') ?></h3>
</div>
<div class="span5 btn">
    <h3><?php echo sprintf($this->translate('Başkalarının hayallerini gerçekleştirmesine yardımcı ol')) ?></h3>
</div>
</div>
</div>

<div class="row">

    <div class="span4">

<div class="hero-unit">
        <h4><?php echo $this->translate('Hep istediğin hediye') ?></h4>
        <p><?php echo $this->translate('Çoğu zaman aldığın hediyeler tam istediklerin olmaz. İster internet bulduğunu, ister resmini çekip yüklediğini, istersen de hayalini yaz paylaş, sevdiklerin aslın. Sen iste yeter!') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Hemen iste') ?> &raquo;</a></p>
</div>
    </div>


    <div class="span4">
<div class="hero-unit">
        <h4><?php echo $this->translate('Eksikler tamamlansın') ?></h4>
        <p><?php echo $this->translate('Haftasonu bir etkinlik mi yapıyorsun? Düğününüz var ve acaba biri bize kahve makinası alsaydı iyi olurdu mu diyorsunuz? Etkinliğinin eskik listesini paylaş ve bırak eksikler isevdiklerin tamamlasın!') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('İsteklerini listele') ?> &raquo;</a></p>
    </div>
    </div>


    <div class="span4">
<div class="hero-unit">
        <h4><?php echo $this->translate('İçeceğin benden') ?></h4>
        <p><?php echo $this->translate('Bir mekanda check-in yaptın ve o da ne? Garson elinde en sevdiğin içeceğinle geliyor. Sen de arkdaşını yalnız bırakma ve gittiği mekanlarda ona en güzelinden birşey ısmarla') ?></p>
        <p><a class="btn btn-success" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('Mutlu et') ?> &raquo;</a></p>
    </div>
    </div>

</div>
